language: elixir
matrix:
  include:
    - otp_release: 20.0
      elixir: 1.6
    - otp_release: 22.0
      elixir: 1.7
    - otp_release: 22.0
      elixir: 1.8
    - otp_release: 21.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.9
sudo: false
script:
  - MIX_ENV=test mix coveralls.travis
